**Name: Kandarp Chaudhary**

**Roll No.: D21016**

## <a id='0'>Index</a>
1) <b>[Vectors:](#0)</b>

[(a)Creating a vector](#1)

[(b)Vector addition, subtraction & scalar multiplication](#3)

[(c)Unit vector](#2)

[(d)Vector Dot Product, Cross Product](#4)

2) <b>[Matrix:](#5)</b>

[(a)Creating a matrix](#6)

[(b)Matrix Transpose](#7)

[(c)Matrix addition, subtraction & scalar multiplication](#8)

[(d)Matrix multiplication](#9)

[(e)Determinant of a matrix](#10)

[(f)Minor and cofactor of a matrix](#11)

[(g)Adjoint of a matrix](#12)

[(h)Inverse of a matrix](#13)

[(i)REF and RREF of a matrix](#14)

[(j)Rank of a Matrix](#15)

3) <b>[Solving linear equations](#18)</b>

4) <b>[Projection of vector u along vector v](#19)</b>

5) <b>[Checking vector independence](#20)</b>

6) <b>[Span](#21)</b>

7) <b>[Change of Basis system](#23)</b>

8) <b>[Norm of a vector](#24)</b>

9) <b>[Eigen Values & Eigen Vector](#25)</b>

10) <b>[Principle Component Analysis](#26)</b>

11) <b>[LU Decomposition](#31)</b>

12) <b>[Differentiation](#27)</b>

13) <b>[Partial Differentiation](#28)</b>

14) <b>[Lagrange Multiplier](#32)</b>

15) <b>[Gradient Descent](#29)</b>

16) <b>[Newton's Function](#30)</b>

17) <b>[Null Space, Row Space & Column Space](#33)</b>

18) <b>[Jacobian Matrix & Determinant](#34)</b>

In [1]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy.linalg import lu
import sympy
import sklearn

<a id='0' style="font-size: 28px">1) Vectors: </a>

<a id='1' style="font-size: 24px">(a)Creating a vector </a>

In [2]:
#creating a vector
A = np.array([1,2,3])
print(A)

[1 2 3]


In [3]:
B = np.linspace(4,6,3)
B

array([4., 5., 6.])

In [4]:
D = np.arange(4)
D

array([0, 1, 2, 3])

In [5]:
E = np.arange(1,9,2)
E

array([1, 3, 5, 7])

In [6]:
#Magnitude of a vector
m = (A[0]**2+A[1]**2+A[2]**2)**0.5
m

3.7416573867739413

[Go to Index](#0)

<a id='3' style="font-size: 24px">(b) Vector addition, subtraction & scalar multiplication </a>

In [7]:
#vector addition
C = np.empty(3)
C = A+B
C

array([5., 7., 9.])

In [8]:
#vector subtraction
C = A-B
C

array([-3., -3., -3.])

In [9]:
#vector scalar multiplication
C = 4*A
C

array([ 4,  8, 12])

[Go to Index](#0)

<a id='2' style="font-size: 24px">(c) Unit vector </a>

In [10]:
#Unit Vector = Vector/Magnitude
u = A/m
u

array([0.26726124, 0.53452248, 0.80178373])

[Go to Index](#0)

<a id='4' style="font-size: 24px">(d) Vector Dot Product, Cross Product </a>

In [11]:
#dot product of two vectors
np.dot(A,B)

32.0

In [12]:
#cross product of two vectors
np.cross(A,B)

array([-3.,  6., -3.])

[Go to Index](#0)

<a id='5' style="font-size: 28px">2) Matrix: </a>

<a id='6' style="font-size: 24px">(a) Creating a matrix </a>

In [13]:
#creating a 3x3 matrix
y = np.random.random((3,3))
y

array([[0.36990182, 0.29930339, 0.85648011],
       [0.22528178, 0.09058959, 0.70959671],
       [0.18723783, 0.83258471, 0.55033684]])

In [14]:
#creating a 3x3 matrix
np.random.normal(0,1,(3,3))

array([[-0.26587509, -1.14401335, -0.37850864],
       [-0.00915769,  2.15181503, -1.09178681],
       [ 0.04244757,  0.17718821, -1.10699718]])

In [15]:
#creating a 3x3 matrix
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#selecting an element of matrix. Indexing starts from 0
x[2,0]

7

In [17]:
#selecting a column of matrix
x[:,1]

array([2, 5, 8])

In [18]:
#selecting a row of matrix
y = x[1,:]
y

array([4, 5, 6])

In [19]:
y[0] = -4 # this also changes the corresponding element in x
y

array([-4,  5,  6])

In [20]:
x

array([[ 1,  2,  3],
       [-4,  5,  6],
       [ 7,  8,  9]])

[Go to Index](#0)

<a id='7' style="font-size: 24px">(b) Matrix Transpose </a>

In [21]:
#finding transpose of a matrix
xt = np.transpose(x)
xt

array([[ 1, -4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

[Go to Index](#0)

<a id='8' style="font-size: 24px">(c) Matrix addition, subtraction & scalar multiplication </a>

In [22]:
#matrix addition
x+xt

array([[ 2, -2, 10],
       [-2, 10, 14],
       [10, 14, 18]])

In [23]:
#matrix subtraction
x-xt

array([[ 0,  6, -4],
       [-6,  0, -2],
       [ 4,  2,  0]])

[Go to Index](#0)

<a id='9' style="font-size: 24px">(d) Matrix multiplication </a>

In [24]:
np.matmul(x,xt)

array([[ 14,  24,  50],
       [ 24,  77,  66],
       [ 50,  66, 194]])

[Go to Index](#0)

<a id='10' style="font-size: 24px">(e) Determinant of a matrix </a>

In [25]:
#finding determinant of a matrix
f = np.array([[1,2,3],[0,1,2],[1,4,1]])
np.linalg.det(f)

-6.0

In [26]:
#finding determinant of a transpose matrix
np.linalg.det(np.transpose(f))

-6.000000000000001

[Go to Index](#0)

<a id='11' style="font-size: 24px">(f) Minor and cofactor of a matrix </a>

In [27]:
#user defined function to find out minor of 'arr' matrix's i row and j row element
def matrix_minor(arr, i, j):
    return np.delete(np.delete(arr,i,axis=0), j, axis=1)

c0 = 0
M = []
C = []
while c0 < len(f):
    c1 = 0
    while c1<len(f[0]):
        Mij = matrix_minor(f,c0,c1)    #Minor of f[c0,c1]
        Cij = (-1)**(c0+c1)            #Co-efficient of |Mij|
        print(Mij, "= M%d%d" %(c0,c1))
        M.append(np.linalg.det(Mij))
        C.append(Cij)
        c1+=1
    c0+=1
M = np.array(M)
C = np.array(C)
print(M)
print(C)

[[1 2]
 [4 1]] = M00
[[0 2]
 [1 1]] = M01
[[0 1]
 [1 4]] = M02
[[2 3]
 [4 1]] = M10
[[1 3]
 [1 1]] = M11
[[1 2]
 [1 4]] = M12
[[2 3]
 [1 2]] = M20
[[1 3]
 [0 2]] = M21
[[1 2]
 [0 1]] = M22
[ -7.  -2.  -1. -10.  -2.   2.   1.   2.   1.]
[ 1 -1  1 -1  1 -1  1 -1  1]


[Go to Index](#0)

<a id='12' style="font-size: 24px">(g) Adjoint of a matrix </a>

In [28]:
#finding adjoint of a Matrix
Cofactor = M*C                                 #Co-factor array
Adjoint = np.transpose(Cofactor.reshape(3,3))
Adjoint

array([[-7., 10.,  1.],
       [ 2., -2., -2.],
       [-1., -2.,  1.]])

In [29]:
#finding adjoint of a Matrix
np.linalg.inv(f)*np.linalg.det(f)

array([[-7., 10.,  1.],
       [ 2., -2., -2.],
       [-1., -2.,  1.]])

[Go to Index](#0)

<a id='13' style="font-size: 24px">(h) Inverse of a matrix </a>

In [30]:
#finding inverse of a matrix as per definition
invf = np.linalg.det(f)**(-1) * Adjoint
invf

array([[ 1.16666667, -1.66666667, -0.16666667],
       [-0.33333333,  0.33333333,  0.33333333],
       [ 0.16666667,  0.33333333, -0.16666667]])

In [31]:
#finding inverse of a matrix
y = np.linalg.inv(f)
y

array([[ 1.16666667, -1.66666667, -0.16666667],
       [-0.33333333,  0.33333333,  0.33333333],
       [ 0.16666667,  0.33333333, -0.16666667]])

In [32]:
#finding inverse of a matrix
np.linalg.matrix_power(f,-1)

array([[ 1.16666667, -1.66666667, -0.16666667],
       [-0.33333333,  0.33333333,  0.33333333],
       [ 0.16666667,  0.33333333, -0.16666667]])

In [33]:
# f*inverse(f) = I3 (3x3 Identity matrix)
z = np.matmul(f,invf)
z

array([[ 1.00000000e+00, -4.44089210e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-8.32667268e-17, -3.88578059e-16,  1.00000000e+00]])

[Go to Index](#0)

<a id='14' style="font-size: 24px">(i) REF and RREF of a matrix </a>

In [34]:
#finding row echolan form of matrix
e = np.array([[1,1],[-1,2]])
from scipy.linalg import lu
lu(e, permute_l=True)

(array([[ 1.,  0.],
        [-1.,  1.]]),
 array([[1., 1.],
        [0., 3.]]))

In [35]:
#finding reduced row echolan form of matrix
sympy.Matrix(e).rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

[Go to Index](#0)

<a id='15' style="font-size: 24px">(j) Rank of a Matrix </a>

In [36]:
#rank of a matrix
np.linalg.matrix_rank(x)

3

[Go to Index](#0)

<a id='18' style="font-size: 28px">3) Solving linear equations </a>

In [37]:
#Solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])
c = np.linalg.solve(a,b)
c

array([-1.,  1.])

In [38]:
#checking if solution is correct or not
np.allclose(np.dot(a,c),b)

True

In [39]:
#Solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:
d = np.linalg.tensorsolve(a,b)
d

array([-1.,  1.])

In [40]:
#checking if solution is correct or not
np.allclose(np.dot(a,d),b)

True

[Go to Index](#0)

<a id='19' style="font-size: 28px">4) Projection of vector u along vector v </a>

In [41]:
#projection of vector a on vector b = (a·b / b·b) * b
u = np.array([6,8])
v = np.array([10,0])
proj_of_u_on_v = (np.dot(u, v)/np.dot(v, v))*v
proj_of_u_on_v

array([6., 0.])

[Go to Index](#0)

<a id='20' style="font-size: 28px">5) Checking vector independence </a>

In [42]:
#Method-1: If Determinant of [u,v] matrix is not zero, then vectors are independent.
D = np.array([u,v])
print("D =",np.linalg.det(D))

#If Determinant of [u,v] matrix is zero, then vectors are dependent.
E = np.array([u,5*u])
print("E =",int(np.linalg.det(E)))

D = -79.99999999999997
E = 0


In [43]:
#Method-2: If RREF of [u,v] matrix has non-zero rows, then vectors are independent.
F = np.array([u,v,5*u])
sympy.Matrix(F).rref()

(Matrix([
 [1, 0],
 [0, 1],
 [0, 0]]),
 (0, 1))

As the third row of RREF matrix consists of only zeros which means,
i) one pair of vectors are a dependent vector or
ii) third vector can be written as linear combination of other two vectors.

In [44]:
#ii) third vector can be written as linear combination of other two vectors, hence third row of RREF Matrix is zero.
G = np.array([[1,1],[-1,2],[2,9]])
sympy.Matrix(G).rref()

(Matrix([
 [1, 0],
 [0, 1],
 [0, 0]]),
 (0, 1))

[Go to Index](#0)

<a id='21' style="font-size: 28px">6) Span </a>

In [45]:
#Span of a single vector or a pair of dependent vector is a line(R^1).
#If vectors are independent, then the span is R^(no. of independent vectors)
H = np.array([[1,1,1],[1,2,3]])
sympy.Matrix(H).rref()
#this combination of vectors will span a R^2 (plane)

(Matrix([
 [1, 0, -1],
 [0, 1,  2]]),
 (0, 1))

In [46]:
H = np.array([[1,1,1],[1,2,3],[2,2,2],[5,5,-8]])
sympy.Matrix(H).rref()
#this combination of vectors will span a R^3 

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 0]]),
 (0, 1, 2))

[Go to Index](#0)

<a id='23' style="font-size: 28px">7) Change of Basis system </a>

<a href='http://www.inf.ed.ac.uk/teaching/courses/cg/lectures/cg3_2013.pdf'>Reference document</a> Refer page:9 for formulas

In [47]:
#i) Translation of basis system
u = np.array([6,8]) #vector-1 in basis system-a
v = np.array([3,4]) #vector-1 in basis system-b
diff = u-v          #calculates difference of origin's co-ordinate between basis system-a and system-b
w = [3,0]           #vector-2 in basis system-a
#Let x be vector-2 in basis system-b then,
x = w-diff
x

array([ 0, -4])

In [48]:
#ii) Scaling of basis system while keeping origin at same place
u = np.array([6,8]) #vector-1 in basis system-a
v = np.array([3,4]) #vector-1 in basis system-b
div = v/u           #calculates ratio of scaling from basis system-a to system-b
w = [3,0]           #vector-2 in basis system-a
#Let x be vector-2 in basis system-b then,
x = div*w
x

array([1.5, 0. ])

In [49]:
#iii) Rotating of basis system while keeping origin at same place and no scaling done
u = np.array([6,8])  #vector-1 in basis system-a
v = np.array([10,0]) #vector-1 in basis system-b
angle = np.arctan(8/6)         #calculates ratio of scaling from basis system-a to system-b
R = np.array([[np.cos(angle), np.sin(angle)],[-np.sin(angle),np.cos(angle)]]) #Rotation matrix for anticlockwise rotation
w = [1,0]            #vector-2 in basis system-a
#Let x be vector-2 in basis system-b then,
x = np.matmul(R,w)
x

array([ 0.6, -0.8])

[Go to Index](#0)

<a id='24' style="font-size: 28px">8) Norm of a vector:</a>

In [50]:
# calculating L1 norm of vector
v = np.array([3,4])
np.linalg.norm(v,1)

7.0

In [51]:
# calculating L2 norm of vector
np.linalg.norm(v,2)

5.0

In [52]:
# calculating L2 norm of vector
np.linalg.norm(v)

5.0

In [53]:
# calculating L3 norm of vector
np.linalg.norm(v,3)

4.497941445275415

[Go to Index](#0)

<a id='25' style="font-size: 28px">9) Eigen Values & Eigen Vector:</a>

In [54]:
A = np.matrix([[1,-1],[-2,0]])
A

matrix([[ 1, -1],
        [-2,  0]])

In [55]:
#finding [A-lambda*I]
lam = sympy.Symbol('lambda')
M = A-lam*np.identity(2)
M

matrix([[1 - 1.0*lambda, -1],
        [-2, -1.0*lambda]], dtype=object)

In [56]:
#|A-lambda*I|=0
Eq = M[0,0]*M[1,1]-M[0,1]*M[1,0]
Eq

-1.0*lambda*(1 - 1.0*lambda) - 2

In [57]:
#Eigen values are roots of Eq
Ev = sympy.solve(Eq,lam)
Ev

[-1.00000000000000, 2.00000000000000]

In [58]:
ans = np.linalg.eig(A)
ans

(array([ 2., -1.]),
 matrix([[ 0.70710678,  0.4472136 ],
         [-0.70710678,  0.89442719]]))

Checking whether A * v = lambda * v or not for lambda = 2:

In [59]:
A = np.matrix([[1,-1],[-2,0]])
v = np.matrix([0.70710678,-0.70710678])
v = np.transpose(v)
np.matmul(A,v)

matrix([[ 1.41421356],
        [-1.41421356]])

In [60]:
lam = 2
lam*v

matrix([[ 1.41421356],
        [-1.41421356]])

Checking whether A * v = lambda * v or not for lambda = -1:

In [61]:
A = np.matrix([[1,-1],[-2,0]])
v = np.matrix([0.4472136,0.89442719])
v = np.transpose(v)
np.matmul(A,v)

matrix([[-0.44721359],
        [-0.8944272 ]])

In [62]:
lam = -1
lam*v

matrix([[-0.4472136 ],
        [-0.89442719]])

Solving one more question:

In [63]:
#getting eigen values
A = np.array([[7,3],[3,-1]])
ans = np.linalg.eigvals(A)
ans

array([ 8., -2.])

In [64]:
#getting eigen values and eigen matrix
ans = np.linalg.eig(A)
ans

(array([ 8., -2.]),
 array([[ 0.9486833 , -0.31622777],
        [ 0.31622777,  0.9486833 ]]))

[Go to Index](#0)

<a id='26' style="font-size: 28px">10) Principle Component Analysis:</a>

In [65]:
D = np.array([[1 , 0.9 ],
       [ 2 ,  2.2],
       [ 3 ,  2.6]])
A = np.transpose(D)[0]
B = np.transpose(D)[1]
#Step-1: Mean centred vactors
mA = A - np.mean(A)
mB = B - np.mean(B)

In [66]:
#Step-2: Find Covariance matrix(CM) for mean centred vactors
CM = np.cov(mA,mB)
CM

array([[1.  , 0.85],
       [0.85, 0.79]])

In [67]:
#Step-3: Get eigen values and eigen vector for CM
x = np.linalg.eig(CM)
print("Eigen values:",x[0])
print("Eigen vector:\n",x[1])
#Total variance = 1+0.79 = 1.75146 + 0.03854 = 1.79

Eigen values: [1.75146074 0.03853926]
Eigen vector:
 [[ 0.74919876 -0.66234524]
 [ 0.66234524  0.74919876]]


In [68]:
#Eigen vectors are orthonormal vectors (Mutually perpendicular and eigen matrix transpose= eigen matrix inverse)
print("Dot product of Eigen vectors =",np.dot(x[1][0],x[1][1]))
print("\nTranspose of Eigen Matrix:\n",np.transpose(x[1]))
print("\nInverse of Eigen Matrix:\n",np.linalg.inv(x[1]))

Dot product of Eigen vectors = 0.0

Transpose of Eigen Matrix:
 [[ 0.74919876  0.66234524]
 [-0.66234524  0.74919876]]

Inverse of Eigen Matrix:
 [[ 0.74919876  0.66234524]
 [-0.66234524  0.74919876]]


In [69]:
#mean centered data set
a = np.transpose(np.array([mA,mB]))
a

array([[-1. , -1. ],
       [ 0. ,  0.3],
       [ 1. ,  0.7]])

In [70]:
#Step-4: Projecting data to the Eigen basis
v = np.matmul(a, np.linalg.inv(x[1]))
v1 = np.transpose(v)
v1

array([[-0.08685352, -0.19870357,  0.28555709],
       [-1.411544  ,  0.22475963,  1.18678437]])

In [71]:
#checking covariance of transformed matrix
cm = np.cov(v1[0],v1[1])
cm

array([[0.06428475, 0.20841586],
       [0.20841586, 1.72571525]])

In [72]:
#checking if total variance remains same as original data (1.79) or not
cm[0,0]+cm[1,1]

1.7899999999999998

In [73]:
# Quadratic equation: (lambda)^2 - 1.79(lambda) + 0.0675
evalues = np.roots([1,-1.79,0.0675])
evalues

array([1.75146074, 0.03853926])

In [74]:
ev1 = CM - evalues[0]*np.identity(2)
ev1

array([[-0.75146074,  0.85      ],
       [ 0.85      , -0.96146074]])

In [75]:
from sklearn.decomposition import PCA
A = np.array([1,2,3])
B = np.array([0.9,2.2,2.6])
c = np.array([A,B])
c = np.transpose(c)
pca = PCA(n_components=2)
pca.fit(c)
print("PCA Components:\n",pca.components_)
print("\nPCA Variance:\n",pca.explained_variance_)
print("PCA Variance Ratio:\n",pca.explained_variance_ratio_)

PCA Components:
 [[-0.74919876 -0.66234524]
 [-0.66234524  0.74919876]]

PCA Variance:
 [1.75146074 0.03853926]
PCA Variance Ratio:
 [0.97846969 0.02153031]


In [76]:
from sklearn.decomposition import PCA
A = np.array([-1,0,1])
B = np.array([-1,0.3,0.7])
c = np.array([A,B])
c = np.transpose(c)
pca = PCA(n_components=2)
pca.fit(c)
print("PCA Components:\n",pca.components_)
print("\nPCA Variance:\n",pca.explained_variance_)
print("PCA Variance Ratio:\n",pca.explained_variance_ratio_)

PCA Components:
 [[-0.74919876 -0.66234524]
 [-0.66234524  0.74919876]]

PCA Variance:
 [1.75146074 0.03853926]
PCA Variance Ratio:
 [0.97846969 0.02153031]


[Go to Index](#0)

<a id='31' style="font-size: 28px">11) LU Decomposition:</a>

In [77]:
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = sp.linalg.lu(A)
print("A:\n",A)
print("P:\n",P)
print("L:\n",L)
print("U:\n",U)

A:
 [[ 7  3 -1  2]
 [ 3  8  1 -4]
 [-1  1  4 -1]
 [ 2 -4 -1  6]]
P:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
U:
 [[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]


[Go to Index](#0)

<a id='27' style="font-size: 28px">12) Differentiation:</a>

In [78]:
#Assigning 'x' as symbol
x = sympy.Symbol('x')
fx = 9*x**4 #function of symbol
# differentiate once wrt x
sympy.diff(fx,x)

36*x**3

In [79]:
# differentiate twice wrt x
x = sympy.Symbol('x')
sympy.diff(fx,x,x)

108*x**2

In [80]:
# differentiate thrice wrt x
x = sympy.Symbol('x')
sympy.diff(fx,x,x,x)

216*x

In [81]:
#product rule for differentiation
fx = sympy.sin(x)*(2*x**2+2)
sympy.diff(fx)

4*x*sin(x) + (2*x**2 + 2)*cos(x)

In [82]:
#chain rule for differentiation
fx = (3*x**3-8)**5
sympy.diff(fx)

45*x**2*(3*x**3 - 8)**4

In [83]:
#to obtain value of differentiation at a given value of x=2
fx = x**3
diff_fx = sympy.diff(fx)
diff_fx_x = sympy.lambdify(x,diff_fx)
diff_fx, diff_fx_x(2)

(3*x**2, 12)

[Go to Index](#0)

<a id='28' style="font-size: 28px">13) Partial Differentiation:</a>

In [84]:
# declare both x and y as variables
x, y, z = sympy.symbols('x y z')
# declare a multi variate function
fxy = 5*x**2*y**5

In [85]:
#Partial differentiation with respect to x
sympy.diff(fxy,x)

10*x*y**5

In [86]:
#Partial differentiation with respect to y
sympy.diff(fxy,y)

25*x**2*y**4

In [87]:
# first partial diff wrt x and then wrt y
sympy.diff(fxy,x,y)

50*x*y**4

In [88]:
# first partial diff wrt x and then wrt y and then again wrt y
sympy.diff(fxy,x,y,y)

200*x*y**3

In [89]:
#partial differentiation with respect to z will give 0 as output when function doesn't contain z
sympy.diff(fxy,z)

0

In [90]:
#to obtain value of differentiation at a given value of x,y,z = (1,1,1)
x, y, z = sympy.symbols('x y z')
fxyz = 5 * z**4 * x**3 * y**2
diff_fxyz = sympy.diff(fxyz,x,y,z)
diff_fxyz_xyz = sympy.lambdify([x,y,z],diff_fxyz)
diff_fxyz, diff_fxyz_xyz(1,1,1)

(120*x**2*y*z**3, 120)

[Go to Index](#0)

<a id='32' style="font-size: 28px">14) Lagrange Multiplier:</a>

In [91]:
x,y,z = sympy.symbols('x y z')
fxy = 6*x+8*y
gxy = x**2+y**2-1
H = fxy+z*gxy
diff_Hx = sympy.diff(H,x)
diff_Hy = sympy.diff(H,y)
diff_Hz = sympy.diff(H,z)
diff_Hx_xyz = sympy.lambdify([x,y,z], diff_Hx)
diff_Hy_xyz = sympy.lambdify([x,y,z], diff_Hy)
diff_Hz_xyz = sympy.lambdify([x,y,z], diff_Hz)
sympy.solve([diff_Hx, diff_Hy, diff_Hz], [x,y,z], simplify=False)

[(-3/5, -4/5, 5), (3/5, 4/5, -5)]

In [92]:
F = sympy.lambdify([x,y], fxy)
G = sympy.lambdify([x,y], gxy)
(F(-3/5,-4/5),G(-3/5,-4/5)),(F(3/5,4/5),G(3/5,4/5))

((-10.0, 0.0), (10.0, 0.0))

[Go to Index](#0)

<a id='29' style="font-size: 28px">15) Gradient Descent:</a>

In [93]:
#obraining function minima using gradiend descent.
x = sympy.Symbol('x')
fx = x**2+3
fx_x = sympy.lambdify(x,fx)
diff_fx = sympy.diff(fx,x)
diff_fx_x = sympy.lambdify(x,diff_fx)
alpha = 0.02
x=5
x_list = []
i_list = []
fx_list = []
diff_x_list = []
for i in range(200):
    i_list.append(i)
    x_list.append(x)
    fx_list.append(fx_x(x))
    diff_x_list.append(diff_fx_x(x))
    x = x - alpha*diff_fx_x(x)
pd.DataFrame({'Iteration':i_list,'Updated x':x_list, 'Gradient at x':diff_x_list, 'f(x)':fx_list})

Iteration  Updated x  Gradient at x       f(x)
0            0   5.000000      10.000000  28.000000
1            1   4.800000       9.600000  26.040000
2            2   4.608000       9.216000  24.233664
3            3   4.423680       8.847360  22.568945
4            4   4.246733       8.493466  21.034739
..         ...        ...            ...        ...
195        195   0.001745       0.003491   3.000003
196        196   0.001675       0.003351   3.000003
197        197   0.001608       0.003217   3.000003
198        198   0.001544       0.003088   3.000002
199        199   0.001482       0.002965   3.000002

[200 rows x 4 columns]

In [94]:
x = pd.Series([-2,1,3,4,5])
y = pd.Series([2,3,5,8,11])
df = pd.DataFrame({'x':x,'y':y})

x, y, w, b = sympy.symbols('x y w b')

# Regression Cost Function
# SSE = (y - (wx + b))**2
cf = (y - w*x -b)**2

# partial derivative wrt w & b
cf_w = sympy.diff(cf, w)
cf_b = sympy.diff(cf, b)
CF_w = sympy.lambdify([x,y,w,b], cf_w)
CF_b = sympy.lambdify([x,y,w,b], cf_b)

#defining a function to calculate the gradient of w & b
def comput_grads(w,b):
    grad_w,grad_b = 0,0
    for i in range(df.shape[0]):
        grad_w += CF_w(df.x[i],df.y[i],w,b) #updating gradient of w with each observation
        grad_b += CF_b(df.x[i],df.y[i],w,b) #updating gradient of b with each observation
    return(grad_w,grad_b)

w,b = 0,0                                   #giving initial values for w and b
alpha = 0.01                                #learning rate
for trial in range(50):                     #iterative calculation for w & b 50 times.
    grad_w, grad_b = comput_grads(w,b)      #calculating gradient of w & b
    w = np.round(w - alpha*grad_w, 4)       #updating value of w
    b = np.round(b - alpha*grad_b, 4)       #updating value of b
    print(trial,w,grad_w,b,grad_b)
print("\nw:",w, " b:",b)

0 2.02 -202 0.58 -58
1 1.6904 32.96 0.6576 -7.759999999999998
2 1.7063 -1.588799999999999 0.8 -14.2352
3 1.6734 3.2929999999999957 0.9246 -12.4614
4 1.6492 2.4152000000000022 1.044 -11.9392
5 1.6254 2.3800000000000168 1.1568 -11.277599999999998
6 1.603 2.24359999999999 1.2635 -10.673200000000001
7 1.5817 2.127000000000006 1.3645 -10.098999999999998
8 1.5616 2.0060000000000002 1.4601 -9.5576
9 1.5426 1.8982000000000028 1.5505 -9.0438
10 1.5246 1.7970000000000077 1.6361 -8.557799999999999
11 1.5076 1.7002000000000024 1.7171 -8.0978
12 1.4915 1.612200000000012 1.7937 -7.661799999999996
13 1.4762 1.526400000000013 1.8662 -7.249999999999997
14 1.4618 1.4383999999999872 1.9348 -6.861600000000002
15 1.4482 1.3636000000000017 1.9997 -6.492399999999999
16 1.4352 1.2953999999999972 2.0611 -6.142600000000002
17 1.423 1.216199999999997 2.1192 -5.8146
18 1.4115 1.1524000000000179 2.1742 -5.501999999999995
19 1.4005 1.0973999999999968 2.2262 -5.205000000000001
20 1.3902 1.031400000000005 2.2755 -4.9

[Go to Index](#0)

<a id='30' style="font-size: 28px">16) Newton's Function:</a>

In [95]:
x = sympy.Symbol('x')
fx=x**2-4
diff_fx = sympy.diff(fx,x)
fx_x = sympy.lambdify(x,fx)
diff_fx_x = sympy.lambdify(x,diff_fx)
x = 1000
x_list = []
i_list = []
fx_list = []
diff_x_list = []
for i in range(15):
    i_list.append(i)
    x_list.append(x)
    fx_list.append(fx_x(x))
    diff_x_list.append(diff_fx_x(x))
    x = x-fx_x(x)/diff_fx_x(x)
print("f(x) becomes zero at x =",x)
pd.DataFrame({'Iteration':i_list,'Updated x':x_list, 'Slope at x':diff_x_list, 'f(x)':fx_list})

f(x) becomes zero at x = 2.0


Iteration    Updated x   Slope at x          f(x)
0           0  1000.000000  2000.000000  9.999960e+05
1           1   500.002000  1000.004000  2.499980e+05
2           2   250.005000   500.010000  6.249850e+04
3           3   125.010500   250.021000  1.562363e+04
4           4    62.521249   125.042497  3.904907e+03
5           5    31.292613    62.585227  9.752277e+02
6           6    15.710220    31.420439  2.428110e+02
7           7     7.982415    15.964831  5.971896e+01
8           8     4.241758     8.483517  1.399251e+01
9           9     2.592382     5.184764  2.720443e+00
10         10     2.067682     4.135364  2.753097e-01
11         11     2.001108     4.002215  4.432159e-03
12         12     2.000000     4.000001  1.226393e-06
13         13     2.000000     4.000000  9.414691e-14
14         14     2.000000     4.000000  0.000000e+00

[Go to Index](#0)

<a id='33' style="font-size: 28px">17) Null Space, Row Space & Column Space:</a>

In [96]:
M = sympy.Matrix([[1,-3,-2],[-5,9,1]])
M_nullspace = M.nullspace()
M_colspace = M.columnspace()
M_rowspace = M.rowspace()
print("Null Space of a matrix :",M_nullspace)
print("\nColumn Space of a matrix :",M_colspace)
print("\nRow Space of a matrix :",M_rowspace)

Null Space of a matrix : [Matrix([
[-5/2],
[-3/2],
[   1]])]

Column Space of a matrix : [Matrix([
[ 1],
[-5]]), Matrix([
[-3],
[ 9]])]

Row Space of a matrix : [Matrix([[1, -3, -2]]), Matrix([[0, -6, -9]])]


[Go to Index](#0)

<a id='34' style="font-size: 28px">18) Jacobian matrix & Determinant:</a>

In [97]:
# declare both x and y as variables
x, y = sympy.symbols('x y')
# declare a multi variate function
f1 = 5*x**2*y**5
f2 = 2*x**4*y**3
M = np.matrix([[sympy.diff(f1,x),sympy.diff(f1,y)],[sympy.diff(f2,x),sympy.diff(f2,y)]])
D = M[0,0]*M[1,1]-M[0,1]*M[1,0]
M, D

(matrix([[10*x*y**5, 25*x**2*y**4],
         [8*x**3*y**3, 6*x**4*y**2]], dtype=object),
 -140*x**5*y**7)

[Go to Index](#0)